language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.1
    - os: osx
      osx_image: xcode8
      dotnet: 1.0.1

script:
  - dotnet --info
  - ./build.sh
