language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-1-003177
    - os: osx
      osx_image: xcode8
      dotnet: 1.0.0-preview2-1-003177

script:
  - dotnet --info
  - ./build.sh
