init:
  - git config --global core.autocrlf input
build_script:
  - ps: .\build\build.ps1
test: off
nuget:
  account_feed: true
  project_feed: true
artifacts:
- path: 'packaging\octokit*.nupkg'
  name: OctokitPackages