init:
  - git config --global core.autocrlf input
build_script:
  - cmd: pushd build
  - dotnet restore --verbosity info
  - dotnet run
  - cmd: popd
test: off
nuget:
  account_feed: true
  project_feed: true
artifacts:
- path: 'packaging\octokit*.nupkg'
  name: OctokitPackages